### ISSUE TITLE
Doesn't take into account conditional scripts.

### ISSUE THREAD

**Issue by NickClark** [schneems/sprockets_better_errors#1]
Good work. It caught an asset I had neglected. But I have one big issue. In my layout file I have some javascript that only gets loaded into the layout when in testing.

``` erb
<%= javascript_include_tag 'test_config' if Rails.env.test? %>
```

I had to remove the gem since I don't want this file to be in my production assets. Is there a preferred/supported workaround.

I noticed you have PR's for this gem in Rails, and I see this as a blocking issue for those.

**Comment by schneems** [comment]
This gem is disabled in production (and actually test as well) by default, so that won't be an issue (https://github.com/schneems/sprockets_better_errors/blob/master/lib/sprockets_better_errors/sprockets_railtie.rb#L6). Maybe you're using version 0.0.1, try updating to 0.0.2?

In this case, the error check is actually inside of the `javascript_include_tag` method, so if it never gets called in development it will never error out.

Sorry for the delay, github doesn't auto subscribe a repo creator to issues :frown:

**Comment by schneems** [comment]
I just released 0.0.3 which gives you the ability to toggle the checks on any environment you like by setting a config flag. If you're having problems please let me know. Currently working with Rails core on getting this functionality worked into master. Better to fix bugs now :)

**Comment by mattbrictson** [comment]
This is quite a tricky problem, and the config flag isn’t a complete solution.

For example, I use the handy [xray-rails](https://github.com/brentd/xray-rails) gem in my projects. This gem is purposely only installed in the `:development` group of the Gemfile. It comes with its own CSS file that it serves via the asset pipeline. This CSS file is never used in production, so it is purposely not added to the precompile list.

However with sprockets_better_errors xray-rails breaks:

```
Asset filtered out and will not be served: add `config.assets.precompile += %w( xray.css )` to `config/application.rb` and restart your server
```

The error message doesn’t make sense, because xray.css is not a production asset. I could add it to the precompile list to silence the error, but that would be misleading.

The only other workaround I can think of is to add a whitelist, like this:

```
config.assets.raise_production_errors = true
config.assets.raise_production_errors.ignore = %w(xray.css)
```

That feels heavy-handed as well.

Thoughts?

**Comment by schneems** [comment]
Sorry for the delay in responding here. I think the best thing here would be to add this to the precompile list in `config/environments/development.rb`.

While it's not semantically the same thing as an `ignore` it has the same result, and will take the same amount of effort from a developer. Since you're never deploying off of the `development` environment it will not actually affect your precompiled file, but only the precompile check. I'm hesitant to add more knobs, especially if they do the exact same thing as existing knobs.

**Comment by mattbrictson** [comment]
Great idea. I agree this is better than adding more knobs. Thanks.

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo
