### ISSUE TITLE
Optionally disable checking Dependencies Improperly Used for images

### ISSUE THREAD

**Issue by nengxu** [schneems/sprockets_better_errors#11]
There is an option for enabling raising sprocket errors;

```
config.assets.raise_production_errors = true
```

But Dependencies Improperly Used errors seem to be an overkill. We may use hundreds of images in our CSS. It would make developers and designers crazy to add: 

```
//= depend_on_asset
```

for each and every image.

But if we don't bother doing so, sprockets_better_errors will become 'annoying' by raising exception for each and every image.

I have to:

```
config.assets.raise_production_errors = false
```

due to this reason.

Please add an option to disable checking Dependencies Improperly Used for images.

Or should we report to the upstream?

Thanks.

**Comment by leods92** [comment]
+1 :+1:

**Comment by schneems** [comment]
I think this is a valid concern. I think a good solution here would be to extend the `depend_on` directive family to accept a directory or a pattern. 

I agree having to put 20 depend on asset directives in a row is insane. 

Another solution could be to get rid of the `depend_on` requirement altogether and store dependencies in the manifest file so that when an `asset_path` is used it could auto add a dependency. 

I think the pain you're feeling here isn't from `sprockets_better_errors`, but rather some functionality missing in sprockets. Using images in your CSS is a totally expected thing, we should make doing the right thing (TM) easier.

**Comment by schneems** [comment]
This was merged into sprockets and is no longer needed. I'm archiving this repo
